# You can find all the emotes at https://github.com/JustTalDevelops/bedrock-emotes?tab=readme-ov-file#emotes
emotes:
  wave:
    id: 4c8ae710-df2e-47cd-814d-cc7bf21a3d67
    name: Wave
  yoga:
    id: 3f1bdf46-80b0-4a64-b631-4ac2f2491165
    name: Yoga

# The cooldown for each hit action for the entities in seconds (Default: 10)
hit-action-cooldown: 10

# The cooldown for the random emote setting for entities in seconds (Default: 60)
random-emote-cooldown: 60

# If true, when a player hits the entity and the entity has a "run_command" hit action, the server performs the command and not the client. (Default: false)
server-command-handling: false